global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['172.17.0.2:5000']
        labels:
          service: 'flask-app'
  
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['172.17.0.8:9091']
        labels:
          service: 'celery-tasks'
